### PR TITLE
add option to not use default scope.

### PR DESCRIPTION
**Pull request by sufleR**
I have a situation when I want all behavior of acts_as_paranoid but don't want to scope records by default.

I have added option to not use default scope and add scope to retrieve not deleted records only.

Default option is false to not break any current behavior.

### CODE REVIEW

**Comment by christopherchiu** [comment]
Hey @sufleR. Thanks for the contribution. Can you explain what is the situation that you're in and why you want this behavior?

**Comment by hidde-jan** [comment]
There are some big problems with `default_scope` in rails. There are currently a handful of issues in rails/rails that show the shortcommings of default_scope and I've been bitten by it in one of my own apps.

Let me show an example. Suppose that we have the following

``` ruby
class Customer < ActiveRecord::Base
  has_many :orders
end

class Order < ActiveRecord::Base
  default_scope { where(deleted_at: nil) }
end

Customer.first.orders.to_sql
=> "SELECT * FROM `orders` WHERE `orders`.`deleted_at` IS NULL AND `orders`.`customer_id` = 1"
```

Suppose that I want to easily get all orders for the customer (including the deleted ones), the only way to do this is to do the following query:

``` ruby
Order.unscoped.where(customer_id: Customer.first).to_sql
=> "SELECT * FROM `orders` WHERE `orders`.`customer_id` = 1"
```

In rails `< 4.0`, this is the only way as far as I know, from `4.0` onwards, we get the `except` and `uscope` methods (http://guides.rubyonrails.org/active_record_querying.html#overriding-conditions), which allows us to remove certain pieces of our query:

``` ruby
# Rails 4.0
Customer.where(name: 'Hidde-Jan').except(where: :name).to_sql
=> "SELECT * FROM `customers`"

Customer.order('email DESC').select('id').where(name: "John")
    .unscope(:order, :select, :where).to_sql
=> "SELECT * FROM `customers`"
```

However, these methods do not work with default_scope, so the following will give an undesired result:

``` ruby
# Rails 4.0
Order.all.unscope(where: :deleted_at)  # Should result in SELECT * FROM `orders`
=> "SELECT * FROM `orders` WHERE `orders`.`deleted_at` IS NULL"
```

This behavior will not be fixed before rails 4.1 according to some of the rails maintainers.

If you need to show deleted objects in a lot of places, then it get's rather hacky really quick.

**Comment by sufleR** [comment]
Sorry for late reply but I was offline.
@hidde-jan great explanation.

@christopherchiu I am building tables which collect statistics in snowlfake schema [wiki](http://en.wikipedia.org/wiki/Snowflake_schema).

Fact table model and main model are in one to one relation.
Main model can be removed but statistics not(it's not my decision).

I define relation as has_one with `dependent: :destroy` and all 'paranoid' magic happens with callbacks.
We use act_as_paranoid elsewhere so  I don't want to write all callbacks. 

Examples where default scope is wrong behavior:
Department is one of dimensions.

``` RUBY
Department.first.task_stats
SELECT "task_stats".* FROM "task_stats" WHERE "task_stats"."department_id" = 1 AND ("task_stats"."deleted_at" IS NULL)
```

It should contain all task_stats.

``` RUBY
Department.includes(:task_stats)
  SELECT "departments".* FROM "departments"
  SELECT "task_stats".* FROM "task_stats" WHERE "task_stats"."department_id" IN (...) AND ("task_stats"."deleted_at" IS NULL)
```

It should also contain all statistics. 

Some of pull requests with "with_deleted" ([example](https://github.com/goncalossilva/acts_as_paranoid/pull/115)) option will be also helpfull to my implementations.

**Comment by zzak** [comment]
In this case I think `acts_as_paranoid` doesn't fit, and you should extend it to fit your needs.

**Pull request closed without merging**
