### PR TITLE
Added to_json on id in instance_eval, to prevent non-numeric primary key from working.

### PR DESCRIPTION
**Pull request by Flink**
Pretty self-explanatory :)

### CODE REVIEW

**Comment by goncalossilva** [comment]
Sorry if this question is dumb, but why would I want to limit primary keys to numeric values?

**Comment by Flink** [comment]
Sorry, I omitted a 'not' before the working in my comment :)

**Comment by goncalossilva** [comment]
Oh, it makes much more sense... merged, thanks!

**Comment by Flink** [comment]
Great ! :)

**Pull request merged**
