### PR TITLE
Rails 4 Support

### PR DESCRIPTION
**Pull request by PeteMichaud**
I made some changes to support rails 4, and it appears to working correctly without deprecation warnings, but I could not get the test suite to load (it has some deprecated stuff in there that I'm not familiar with, and it says I don't have Bundler installed even though I do). So this need to be legitimately tested, but it works in my project, so I think it's probably close if not there already. 

I also changed some behavior that may be controversial. The change might be good as an option, actually.  on ln 129 of `core.rb` I changed it to use self.update_column, and as a result the deleted_at columns are reverted to nil, but no active record callbacks take place. This is the behavior I needed in my project, and it may be the correct behavior in general, but I'm not sure. Like I said, it could also be an option like `:recover_with_callbacks` or something like that.

### CODE REVIEW

**Comment by zlx** [comment]
Great! :+1:

**Comment by mmay** [comment]
+1 Would it be possible to get a Rails4 branch going?

**Comment by anicholson** [comment]
+1, a rails4 branch would be excellent

**Comment by ausangshukla** [comment]
+1, for a rails4 branch

**Comment by SailorMercury** [comment]
+1

**Comment by shamil614** [comment]
+1

**Comment by allaire** [comment]
:+1: Using this branch temporally

**Comment by chrismhilton** [comment]
I'm also using this branch temporarily but just discover an issue with the belongs_to_with_deleted method.

I'm trying to create a belongs_to association with a scope as the conditions option is now deprecated, however, the belongs_to_with_deleted method does not include a scope argument.

Rails 3 association definition:

```
belongs_to :activity_type, :class_name => "ListValue",
                           :foreign_key => :type_id,
                           :conditions => {:list_name_id => ListName::IDS[:Activity_Type]}
```

Rails 4 association definition:

```
belongs_to :activity_type, -> { where(:list_name_id => ListName::IDS[:Activity_Type]) },
                           :class_name => "ListValue",
                           :foreign_key => :type_id
```

Rails 4 ActiveRecord belongs_to method definition:

```
def belongs_to(name, scope = nil, options = {})
```

ActsAsParanoid belongs_to_with_deleted method definition:

```
def belongs_to_with_deleted(target, options = {})
```

**Comment by chrismhilton** [comment]
I have switched to using the rails4.0 branch from https://github.com/byroot/rails3_acts_as_paranoid which also has an associated pull request https://github.com/goncalossilva/acts_as_paranoid/pull/102

**Comment by cyril-sf** [comment]
radar/paranoia seems to be the de facto Rails 4 gem for soft deletion

**Comment by zzak** [comment]
We are no longer maintaining this fork, please resubmit this to the upstream: https://github.com/technoweenie/acts_as_paranoid

**Pull request closed without merging**
