### PR TITLE
Fix nil polymorphic, with_deleted, belongs_to

### PR DESCRIPTION
**Pull request by periclesd**
When association is polymorphic and association is not set, finder should return nil

see https://github.com/goncalossilva/rails3_acts_as_paranoid/issues/61

### CODE REVIEW

**Comment by goncalossilva** [comment]
I'm confused, since this was closed. Should I consider this or wait?

**Comment by periclesd** [comment]
i had some trouble with the commits, re-opened as https://github.com/goncalossilva/rails3_acts_as_paranoid/pull/65

**Comment by chuckg** [comment]
What problem is this solving? The line:

``` ruby
return #{target}_without_unscoped(*args) unless association.klass.paranoid?
```

This returns the default result of any query, whether it should be nil or not. It appears to only fix the situation where someone incorrectly sets up an association and the class doesn't load properly, in which case, your application has bigger problems than how acts as paranoid is handling deleted records.

**Comment by goncalossilva** [comment]
@pericles, could you answer @chuckg's question? He's a maintainer of this repo and the main contributor to this recent rewrite, so I value his opinion greatly.

**Comment by periclesd** [comment]
https://github.com/goncalossilva/rails3_acts_as_paranoid/issues/61
If the polymorphic association is not set, old code would break. This pull should not be merged.

**Pull request closed without merging**
