### PR TITLE
Add support for string type with non-nil values when not deleted

### PR DESCRIPTION
**Pull request by aake**
This is pretty much accomplishing the same thing as @garysweaver did with pull request #73.

There are two main differences:
- Make sure records with non-nil values in the deleted column are not actually deleted (for real) unless the column value matches the deleted_value. They will be deleted on a second destroy as expected.
- The tests added are isolated from the previously existing tests and do not modify the test setup. This was requested by @chuckg in reference to pull request #73.

### CODE REVIEW

**Comment by garysweaver** [comment]
Sorry, I've not had time to redo the test I had rewritten to meet the test specifications mentioned in #73. Feel free to axe my pull request and use this if it does the same thing and they have time to make the tests kosher. Note that the test(s) I included in #73 worked and did the job, they just weren't approved.

**Comment by chuckg** [comment]
Thanks for the effort, @aake and @garysweaver, I've merged your changes and pushed them to the 3.2 branch. I don't have access to the rubygems and I'm not 100% sure how he's managing master vs the different rails version, so we'll have to wait for @goncalossilva to push the changes out officially.

**Comment by goncalossilva** [comment]
Sounds good.

@chuckg Send me a message with your email and I'll give you access on rubygems and explain the versioning logic I'm using :-)

**Comment by aake** [comment]
Just to follow-up - will there be a new version of the gem soon including these changes?

**Comment by goncalossilva** [comment]
@aake Yes!

**Comment by aake** [comment]
@goncalossilva Thanks!

**Pull request merged**
