### PR TITLE
Don't fail when trying to remove an unsaved object

### PR DESCRIPTION
**Pull request by dmathieu**
When trying to destroy an unsaved object (this happens in some of our tests), acts as paranoid tries to remove the object, and calls it's id for that with

```
Array(self.class.primary_key), Array(self.id)].transpose
```

As `self.id` is nil, transpose can't work because the array is missing an entry.
And we don't need to run any sql query to remove an object if nothing has been saved into the database yet.

### CODE REVIEW

**Comment by avit** [comment]
Confirmed, I'm seeing this problem here too. This pull request fixes it. :thumbsup: 

Problem appears as:

```
Exception: IndexError: element size differs (0 should be 1)
--
0: /var/lib/gems/1.9.1/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:206:in `rescue in transaction'
1: /var/lib/gems/1.9.1/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:180:in `transaction'
2: /var/lib/gems/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:208:in `transaction'
3: /var/lib/gems/1.9.1/gems/activerecord-3.2.11/lib/active_record/associations/has_one_association.rb:14:in `replace'
4: /var/lib/gems/1.9.1/gems/activerecord-3.2.11/lib/active_record/associations/singular_association.rb:17:in `writer'
```

**Comment by HoneyryderChuck** [comment]
Me too.

**Comment by kuboon** [comment]
how about destroy! method?

**Comment by dmathieu** [comment]
@kuboon: the destroy! method has been implemented only in rails 4. This pull request has no meaning to adding the support of rails master.

**Pull request closed without merging**
