### PR TITLE
Rails 3.2, default scope support, chainable scopes/associations

### PR DESCRIPTION
**Pull request by chuckg**
A collection of updates and enhancements.  I also did a pretty large reorganization of the code (created a `ActsAsParanoid::Core`).
- Updated to support Rails 3.2 (strictly)
- Added support for multiple default scopes on a model 
- Added tests around Klass.paranoid?
- Added tests around deletion through a relation:
  - Fake removal:
    
    ```
      ParanoidObject.scope.destroy(object_id)
      paranoid_object.has_many_association.order(:id).destroy_all -> hooks into object.destroy
    ```
  - Real removal:
    
    ```
      ParanoidObject.scope.destroy!(object_id)
      paranoid_object.has_many_association.order(:id).destroy(has_many_association_object_id)
      paranoid_object.has_many_association.only_deleted.destroy(has_many_association_object_id)
      paranoid_object.has_many_association.order(:id).destroy_all
      paranoid_object.has_many_association.only_deleted.destroy_all
      paranoid_object.has_many_association.order(:id).delete_all!
    ```
- `with_deleted` and `only_deleted` are fully chainable with scopes and relations:
  
  ```
  Object.some_scope.with_deleted == Object.with_deleted.some_scope
  Object.only_deleted.where(..) == Object.where(..).only_deleted 
  ```
- Added `:with_deleted` option to `belongs_to` (taken from and modified slightly: https://github.com/goncalossilva/rails3_acts_as_paranoid/pull/48)
## 

Fixes:
- https://github.com/goncalossilva/rails3_acts_as_paranoid/issues/50

### CODE REVIEW

**Comment by goncalossilva** [comment]
This is great. I'm just in the process of cleaning up this gem and organizing it per Rails version and this comes in the perfect time. Thanks!

**Comment by goncalossilva** [comment]
Would you agree that the only change that should be made in the README is to remove the caveat part regarding using another default_scope?

**Comment by chuckg** [comment]
Definitely, the caveat around additional default_scopes can be removed.  In addition it might be useful to add:
- Notes about deletion through relations and associations
- Chainable scopes/associations when using `with_deleted`/`only_deleted`
- Support for the `:with_deleted` option on a `belongs_to` association

There are snippets about these features in the pull request comments above.

**Comment by goncalossilva** [comment]
Awesome, thanks! I'll look into those snippets.

**Comment by goncalossilva** [comment]
I've just merged your changes. Great code, thank you!

I've also updated the README. If you find some time, please take a look and feel free to fix/improve anything you notice is missing.

**Pull request merged**
