### PR TITLE
Added validates_uniqueness_of_with_deleted from the original AAP

### PR DESCRIPTION
**Pull request by copyhacker**
Hi,
I needed uniqueness validation to work with a paranoid model, so I added it. :) Have a look.
  -Jonathan.

### CODE REVIEW

**Comment by goncalossilva** [comment]
Hi,

Thanks for your contribution! I've noticed that you added yourself as an author to the gem... I don't mind that at all, as long as you are available to maintain the new validation.

So... are you?

**Comment by copyhacker** [comment]
Whoops, that was just because I needed to push my fork to rubygems so my work project could use it. You can take my name back out of the gemspec, but I'll be happy to look at any issues that come up with my code.

**Comment by copyhacker** [comment]
You'll also want to merge from my HEAD instead of the commits in this pull request. I made a bunch of fixes.

**Comment by goncalossilva** [comment]
Ok, I think I've merged all your changes. All tests pass.

However, I made a small change: If the user wants to use paranoid validations, he must explicitly say so by extending his class with "ActsAsParanoid::Validations".

Are you OK with this? If so, I'll push the changes.

**Comment by copyhacker** [comment]
What do you think about adding a validates_as_paranoid macro to wrap that, instead of the explicit extends?

**Comment by goncalossilva** [comment]
Yeah, it looks better. I'll add it — thanks for the suggestion!

One last request... could you explain this new feature in the documentation?

**Comment by copyhacker** [comment]
Sure, I'll write something up and send you another pull request when done. Thanks.

**Comment by goncalossilva** [comment]
Just committed your changes... sorry for taking so long. Also added the validates_as_paranoid wrap you suggested. Thanks for your contribution and happy holidays!

**Pull request merged**
