### PR TITLE
Fix of element size differs. + Checking persisted

### PR DESCRIPTION
**Pull request by noma4i**
Error: **Element size differs (1 should be 2)**

Why?

Was:

```
>> Array(self.class.primary_key)
=> ["i", "d"]
```

Correct:

```
>> Array.wrap(self.class.primary_key)
=> ["id"]
```

I think this is Ruby 1.9.3 Issue.

### CODE REVIEW

**Comment by noma4i** [comment]
Nobody cares? Ok.

**Comment by chuckg** [comment]
Hi noma4i,

I couldn't reproduce the results you have on `ruby 1.9.3p194`, but that's not to say it's not happening on other versions. Which are you on? 

Also curious what the steps were for reproducing the error: `Element size differs (1 should be 2)`

Started with: `rails generate model Human`

In console:

``` ruby
1.9.3p194 :001 > Array(Human.primary_key)
 => ["id"] 

1.9.3p194 :007 > Array.wrap(Human.primary_key)
 => ["id"] 

1.9.3p194 :025 > Array[Human.primary_key]
 => ["id"] 

1.9.3p194 :027 > Array.[](Human.primary_key)
 => ["id"]

# Now with a composite key
1.9.3p194 :028 > composite_primary_key = [:user_id, :group_id]
 => [:user_id, :group_id] 

1.9.3p194 :029 > Array(composite_primary_key)
 => [:user_id, :group_id] 

1.9.3p194 :030 > Array.wrap(composite_primary_key)
 => [:user_id, :group_id] 

1.9.3p194 :031 > Array[composite_primary_key]
 => [[:user_id, :group_id]] 

1.9.3p194 :032 > Array.[](composite_primary_key)
 => [[:user_id, :group_id]]  
```

Odd, no? Although `wrap` is a part of ActiveSupport, I think it does add some readability to the otherwise bracket clusterfuck that's going on in that line. I'm never sure whether it's smart to stick to the default Ruby API for gems so as to avoid collision with the changing Rails landscape, but in this case adding a `flatten` would be even worse.

**Comment by avit** [comment]
Your `persisted?` check (see also #94) looks right.

I don't see the issue with `["i", "d"]` that you're having either, mine is "0 for 1"; I assume you have a 2-column composite key here.

What transpose is doing there (I assume) is converting `[[:id1, :id2], [1, 2]]` into `[[:id1, 1], [:id2, 2]]`. That gets passed to Hash like this:

``` ruby
# primary_keys = [:id1, :id2]
# id = [1, 2]
[[:id1, :id2], [1, 2]].transpose == [[:id1, 1], [:id2, 2]]
Hash[[[:id1, 1], [:id2, 2]]] == {:id1 => 1, :id2 => 2}
```

The Array.wrap doesn't look like it's necessary. Standard ruby Array() kernel method should work fine like it is.

**Comment by chuckg** [comment]
@avit: That's precisely what the transpose is up to.  

I'd like to hold off on this change (to `Array`) until we figure out what version of Ruby @noma4i is running on.  I can't reproduce the same problem with `Array()` not marshaling correctly.

**Comment by noma4i** [comment]
Ok, looks like this was my local issue. Thanx!   

## 

Polite as usual

**Comment by chuckg** [comment]
Going to close this one. I believe it was fixed in #94.

**Pull request closed without merging**
