### PR TITLE
Add :with_deleted option to belongs_to

### PR DESCRIPTION
**Pull request by donv**
This option allows depending objects to access the dependent after it is soft-deleted.  This was present in acts_as_paranoid and is useful for us.

Can you add this for the next release?

### CODE REVIEW

**Comment by HoneyryderChuck** [comment]
Hi,

This does not work when the association is polymorphic (or better said, the polymorphic association does not work if there is a with_deleted involved).

**Comment by donv** [comment]
I'd be happy to work more on this.  Do you perhaps have a test for the polymorphic case?

**Comment by HoneyryderChuck** [comment]
Hi, glad that you're on the subject. So, here it goes:

class SuperFreak < ActiveRecord::Base

```
belongs_to :loveable, :polymorphic => true, :with_deleted => true
```

end

So, the class of my loveable association will be defined on the loveable_class column. However, when i try to fetch it, it says the class "Loveable" does not exist (and rightfully so). This is mainly due to this snippet:

options[:class_name] || target.to_s.classify (line 213)

In the polymorphic case, neither is the class associated by class_name nor it should be created from the association target. I tried to correct this, but it seems I don't have a reference to the object whose association i'm trying to fetch. Maybe your ActiveRecord powers are mightier. Godspeed.

**Comment by HoneyryderChuck** [comment]
Hey man,

I think i came up with a relatively good workaround for the polymorphic thing. So, here is my input:

<pre>
<code>
(#{options[:polymorphic].present?} ? send("#{target}_type").constantize : #{options[:class_name] || target.to_s.classify}).unscoped { #{target}_without_unscoped(*args) }
</code>
</pre>


that is, of course, my replacement for that line i mentioned on the previous comment. If you have a different more elegant workaround, please let me know.

Cheers

**Comment by paulcc** [comment]
Hi

A suggestion until (or instead of) this code gets added: add a brief note in the Readme of this repo explaining how to implement the effects of the old :with_deleted option in a particular model. This will save others some digging. 

Paul

**Comment by goncalossilva** [comment]
Pulled from #55. Thanks!

**Comment by tak2siva** [comment]
Hi

I have duplicated :belongs_to code for :has_many relationship 

but it looks like the code is not executed in with_deleted scope

Can anybody correct me

https://github.com/tak2siva/acts_as_paranoid/blob/master/lib/acts_as_paranoid/associations.rb

**Pull request closed without merging**
