### PR TITLE
Recursive recover

### PR DESCRIPTION
**Pull request by cheerfulstoic**
I thought I had done a pull request for this earlier, but apparently it didn't go through!

I extended the recover method here to allow for recursive recovery of object associations so that, taking a Blog as an example, recovering an Article object would automatically recover the associated Comment objects if they were marked as :dependent => :destroy.

For time-based paranoid fields, it can also recursively recover those associated objects within a certain time frame so that you only get the ones that were deleted at the same time as the main object.

I've also included tests.

### CODE REVIEW

**Comment by goncalossilva** [comment]
Recursive recovery sounds good.

The only thing I was unsure about was the time-based recovery. It honestly doesn't make much sense to me... care to explain why this would be useful?

Also, do you mind adding some documentation regarding the new feature and its options?

Thanks.

**Comment by cheerfulstoic** [comment]
Sure, I'd be glad to add some documentation.

To explain the timestamp recovery, taking a blog Post model as an example where a post has_many Comment objects.  If there's a Post that's been around for a while, perhaps a couple of Comments were deleted in the past, leaving the Post with 5 Comments (and 3 deleted Comments).  If the Post is deleted, the 5 associated Comments are also deleted around the same time (basically as quickly as rails can traverse the dependent associations).  If we wanted to recover that Post, we would only want to recover the 5 Comments that were deleted at the same time as the Post and leave the other 3 deleted.

**Comment by goncalossilva** [comment]
I think I'm still missing the point... why would we fake delete the 2 comments previously? Why wouldn't we delete them permanently (assuming they were delete because there was something wrong with them) in the first place?

**Comment by cheerfulstoic** [comment]
Because we're paranoid and don't ever want to delete anything permanently  ;)

A blog might not be as good of an example, though, because offering up some UI to allow users to undelete their comments might be a bit extreme.  At the company I work for, however, we use acts_as_paranoid extensively to make sure that we can always recover something for our clients (even if we need to recover it through the Rails console).  It would also be ideal if we could restore a complex set of associations (and we have a number of sets of models with complex associations) to their state at the point of deletion and then be able to further undelete parts after the fact that were deleted before the deletion of the main object.  I could list an example, but I don't remember to what extent I'm limited by my company's NDA.

**Comment by goncalossilva** [comment]
Hello!

Just to let you know that I haven't forgot this. I'm still not sure about the time-based recursive recovery. Some computers are slow, the database can freeze sometimes, etc... many situations in which time-based recovery would have a strange behavior.

Anyway, I've given it some thought and my conclusion is: Why not? As long as it stays out of the way of the ordinary user who doesn't care about this feature, I can't see any reason for it to be absent. I'll just increase the default time a bit, ok?

Thanks for your contribution!

**Comment by cheerfulstoic** [comment]
Great, thanks ;)  Feel free to increase the default time.  I also just pushed a change that fixed a bug where the recursive recover was trying to recover non-paranoid models through associations.  I was holding off committing it because I wanted to test it, but if you're going to be pulling soon it should be included.  I'll build some tests shortly, though.

Thanks again

**Comment by goncalossilva** [comment]
Oh, ok. I would prefer to wait for the tests. Maybe I can help?

**Comment by cheerfulstoic** [comment]
Of course you're right ;)  Tests for these conditions committed

**Comment by goncalossilva** [comment]
Just merged your changes, sorry for taking so long. I also increased the default time window to 5 minutes. Thank you for your contribution! Happy holidays.

**Comment by cheerfulstoic** [comment]
Great, thanks!

**Pull request merged**
