### PR TITLE
Make mass assignment of the paranoid column an option.

### PR DESCRIPTION
**Pull request by donv**
Added an option to the acts_as_paranoid method to make the paranoid column mass assignable:

``` Ruby
class Foo < ActiveRecord::Base
  acts_as_paranoid :mass_assignable => true
end
```

### CODE REVIEW

**Comment by christopherchiu** [comment]
@donv Hey donv, I just committed a new version that fixes Travis CI. Could you pull and merge those changes? Let me know if you're too busy, I can do it in a separate branch if necessary.

**Comment by donv** [comment]
Sorry for the mess.  Still learning GIT...  Is it OK?  Travis build succeeds.

**Comment by christopherchiu** [comment]
Looks good. Can I ask, what's your specific use case?

**Comment by donv** [comment]
We replicate our PostgreSQL server database using messaging to clients running DerbyDB.  The DB is replicated using messaging and the messages are compressed YAML including the changed attributes of the ActiveRecord objects.  These attributes include `deleted_at` and need to be set on the receiving object like any other attribute.

This PR requires us to set `:mass_assignable => true` on every use of `acts_as_paranoid`.  A global setting would be better for us.  Even better, the column could be mass assignable by default, and the option would be to make it protected.  :)

**Comment by christopherchiu** [comment]
My guess is that the original motivation was to have that field be as transparent as possible, and having it be mass assignable by default does seem to break some of that principle. However, I do think there are some use cases for it, like your own, and having it as an option seems to be the right amount of complexity.

**Comment by christopherchiu** [comment]
@donv Thank you for contributing. And for tests!

**Pull request merged**
