### PR TITLE
extending deletion column type to include string type datatable fields

### PR DESCRIPTION
**Pull request by vikramdhillon**
I had made changes to the gem to fulfill the requirements of my project, which were to have the deletion column in datatable as a string field. This worked for me , hope it can be helpfull to others too.

### CODE REVIEW

**Comment by germs12** [comment]
This would be great for me!  We are not using a date or a flag to determine what is deleted.  We use a code which is a string.  Any chance this will be pulled in to the original gem?

**Comment by vikramdhillon** [comment]
hi germs12 , 
i have only as much idea as you if it will be pulled :)  . . i haven't heard anything from the original author.

**Comment by goncalossilva** [comment]
Sorry for taking so long, I missed a lot of notifications recently. I'll take a look at this during the rest of the week.

**Comment by goncalossilva** [comment]
Hello,

I took a look at this and loved the suggestion, thanks!

I implemented it a bit differently, though... check https://github.com/goncalossilva/rails3_acts_as_paranoid/commit/57f629b2c28f44b5da382f4a1e2cc3756f48cabe

Once again, thank you for the initial implementation of this idea!

**Comment by vikramdhillon** [comment]
Hi Gonçalo, 

Glad to hear my contribution was of value. I'm still pretty new to Rails so this is a big deal for me :)

regards,
Vikram

**Pull request closed without merging**
