### PR TITLE
ActiveRecord queries with includes now respect :with_deleted => true

### LINKED ISSUE #62: ActiveRecord queries with :includes do not respect :with_deleted => true
I can't see a way around the N+1 problem without using :includes in my Active Record queries. Per the documentation:

``` ruby
class ParanoiacParent < ActiveRecord::Base
    has_many :children, :class_name => "ParanoiacChild"
end

class ParanoiacChild < ActiveRecord::Base
    belongs_to :parent, :class_name => "ParanoiacParent"
    belongs_to :parent_with_deleted, :class_name => "ParanoiacParent", :with_deleted => true
end
```

However if the following is called in a controller:

``` ruby
@paranoiac_children = ParanoiacChild.includes(:parent_with_deleted).all
```

The log load statement shows a "('paranoiac_parents'.'deleted_at' IS NULL)" in the WHERE clause resulting in `undefined method` errors. I guess I'm forced to avoid using :includes. Is this behavior by design?

### PR DESCRIPTION
**Pull request by tkupari**
Check for with_deleted option when building scope for includes.  Fixes #62

### CODE REVIEW

**Comment by zpieslak** [comment]
This should be merged. I'm currently working on @tkupari's fork instead of official one.

**Comment by aaronchi** [comment]
+1

**Comment by markedmondson** [comment]
+1

**Comment by tkupari** [comment]
Closing this dead pull request as I have deleted my fork

**Pull request closed without merging**
