### PR TITLE
Changes to rails3_acts_as_paranoid for Rails 3.1

### PR DESCRIPTION
**Pull request by softcraft-development**
I'm hacking around in rails3_acts_as_paranoid. In the process of making my own changes (which I hope to fill you in on later), I found the errors (mentioned [here](https://github.com/goncalossilva/rails3_acts_as_paranoid/issues/40)) caused by using the Rails 3.1 version of ActiveRecord... and managed to fix them.

There's only 3 changes of real importance:
- Rename the call in uniqueness_without_deleted.rb from mount_sql_and_params to build_relation
- In the same call, pass an Arel::Table instead of a String table name.
- Remove the aliasing of primary_key_name to foreign_key in ActiveRecord::Reflection::AssociationReflection

Feel free to ignore/revert my changes to the Gemspec; those are mostly for my own internal purpose.

Hope this helps,

Craig

### CODE REVIEW

**Comment by goncalossilva** [comment]
I haven't put much thought to it, but I wonder how easy it would be to have one single gem for both versions (3.0 and 3.1) without a bunch of if statements.

**Comment by softcraft-development** [comment]
As it happens, I just spent a bunch of time on reworking some other changes from 3.0 to 3.1. The changes were pretty significant... the whole AR class structure changed dramatically in 3.1.

So, from my perspective at least, the answer would be "no". 

Now, my major changes aren't necessarily good to pull into your main repo, as they take a bit of a functional detour. I was planning on sending you a full explanation later. In the meantime though, you might be interested in a [sneak preview](https://github.com/goncalossilva/rails3_acts_as_paranoid/compare/84415bb7c162238c1cee24f526f5b6397c30ff2b...d030f1fe09b06d101edd76aa45bf975bc2cb4429).

**Comment by goncalossilva** [comment]
Thanks for the link, I'll take a look... and I'll wait for your explanation later, when you find the time.

I'm thinking I could separate 3.0/3.1-specific code into modules. Then it would be a single conditional statement.

**Comment by chrismhilton** [comment]
When using Rails 3.1 in conjunction with the latest version 0.1.3 of rails3_acts_as_paranoid, I encountered the same issue which the software-development fork commit [Removed aliasing of primary_key_name to foreign_key](https://github.com/softcraft-development/rails3_acts_as_paranoid/commit/819f99a6e6a904510eb132a40a61be1b076bc02f) deals with ie.

a multitude of these log messages:

DEPRECATION WARNING: primary_key_name is deprecated and will be removed from Rails 3.2 (use foreign_key instead).

eventually resulting in:

SystemStackError (stack level too deep)

I've partly added this comment as it took a while to track down that rails3_acts_as_paranoid was the culprit as the software-development fork commit comment didn't show up in google. I can see that the software-development fork has catered for a number of Rails 3.1 changes, however, in this particular instance it may be possible to cater for both Rails 3.0 and 3.1 by using the following:

```
ActiveRecord::Reflection::AssociationReflection.class_eval do
  alias_method :foreign_key, :primary_key_name unless instance_methods.include?(:foreign_key)
end
```

**Comment by goncalossilva** [comment]
Merged this from the other PR.

**Pull request closed without merging**
