### PR TITLE
README clarification

### PR DESCRIPTION
**Pull request by chuckg**
Adding the `:with_deleted` to a `belongs_to` association does not create two association accessors, you still need to explicitly create one including deleted records and (or one without).

### CODE REVIEW

**Comment by chuckg** [comment]
I should also mention that I was developing entirely on `ree-1.8.7-2011.03` while doing the upgrade for Rails 3.2.  Not sure if you want to add that to the README as well.

**Comment by goncalossilva** [comment]
The tests hang on my REE build. Do they run on yours?

**Comment by chuckg** [comment]
Yup:

``` sh
$ rvm current
ree-1.8.7-2011.03@aap

$ ruby -Itest test/test_core.rb
Loaded suite test/test_core
Started
...
Finished in 1.193894 seconds.

16 tests, 110 assertions, 0 failures, 0 errors
```

This is on e4d3676bbf96f74b11f51bcb364e3bb613db8bd3 from master.

**Comment by goncalossilva** [comment]
That's only test_core, but you're right — I was just able to run all of them successfully. I'm not entirely sure if I want to add it to the README though, since I don't intend to actively monitor 1.8 compatibility.

**Pull request merged**
