### PR TITLE
Rails 4.0.0.beta1 compatibility

### PR DESCRIPTION
**Pull request by byroot**
- Update dependencies
- Get rid of observers tests (I tried to use rails-observer gems but it was a mess)
- Update deprecated calls like #scope or #default_scope without block
- Get rid of attr_protected call and tests
- Get rid of AR#destroy! NoMethodError test

The last one cause issue because in AR 4 #destroy! bang is defined.
It's the same as #destroy but raise an AR::RecordNotFound if the record
is not present in database.

It may be smart to find another name for this method. But for now it just works.

### CODE REVIEW

**Comment by aaronchi** [comment]
:+1:

**Comment by yuki24** [comment]
@byroot, @goncalossilva, please review the PR I just sent: byroot/rails3_acts_as_paranoid/pull/1

**Comment by taylorbrooks** [comment]
+1

**Comment by lesyk** [comment]
+1

Rails 4.0.0.beta1 compatibility?
Yesterday Rails 4.0.0.rc2 was introduced.

**Comment by atipugin** [comment]
+1, any news on it?

**Comment by goncalossilva** [comment]
@byroot Now that Rails 4 is out, would you be willing to fast-forward your changes and ensure everything works so that me or @chuckg can take a look at it?

**Comment by XORwell** [comment]
+1

**Comment by Curter29** [comment]
+1

**Comment by nzaillian** [comment]
+1

**Comment by christopherchiu** [comment]
Hi guys, I'm going to be actively working on getting this gem compatible with Rails 4. I'm still getting through all the pull requests and issues but I'll keep you guys updated.

**Comment by hamadmj** [comment]
+1

**Comment by chrismhilton** [comment]
+1

**Comment by RobinClowers** [comment]
@christopherchiu any word on this? I'm working on upgrading an app to 4 and I'm not sure which fork to use. Anything I could do to help?

**Comment by zzak** [comment]
We're working on this separately, and will be cherry-picking some of these commits separately.

I'm going to close this since its still WIP.

**Pull request closed without merging**
