### PR TITLE
Fixing support for string type not to ignore records with column value other than the user-specified non-nil deleted_value

### LINKED ISSUE #72: column: 'some_column', column_type: 'string', deleted_value: 'some_value' options do not seem to work
Have a model in Rails 3.2.6, Ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin11.4.0] like:

```
class SomeModel < ActiveRecord::Base

  set_primary_key :some_id

  acts_as_paranoid column: 'some_column', column_type: 'string', deleted_value: 'some_value'

  has_many :other_models

end
```

There are four rows of data in this table and the value in some_column is populated but is not 'some_value'. However, SomeModel.count returns 0 when using latest rails3_acts_as_paranoid 0.2.4. If I comment acts_as_paranoid in the model, then SomeModel.count returns 4.

### PR DESCRIPTION
**Pull request by garysweaver**
This is to resolve: https://github.com/goncalossilva/rails3_acts_as_paranoid/issues/72

Summary:

Fixing support for specifying a non-nil deleted_value with string type, so that if the column contains a value other than the deleted_value, the record won't be considered to be deleted. Also added tests for this.

Explanation:

With this patch you can have values in the column like "not deleted" and the record would not be considered deleted, but if the value was the same as the deleted_value like "deleted" then the record would be considered deleted.

I would hope this would be backwards compatible with how people were using it, although if they had assumed that if any value was in the column that the record should be considered deleted, then this patch would not be backwards compatible. However, since I had gotten the impression that records not marked with the deleted_value were not deleted, my assumption is that this patch makes it behave more like users of the gem would expect.

### CODE REVIEW

**Comment by garysweaver** [comment]
For a second there I thought it wasn't working, but realized I needed to specify the rails3.2 branch I made the change in the Gemfile:

```
gem 'rails3_acts_as_paranoid', :git=>'git://github.com/garysweaver/rails3_acts_as_paranoid.git', :branch => 'rails3.2'
```

**Comment by aake** [comment]
+1 on this pull request. I work an a legacy system that has a lot of Y/N flags for deleted records with no NULLs. I think this is pretty common in legacy databases in general.

**Comment by chuckg** [comment]
Spot on, this makes total sense and even agrees with the language in the README:

"If your column type is a string, you can also specify which value to use when marking an object as deleted by passing :deleted_value (default is "deleted")."

It might be made more clear by adding "_... as deleted by passing :deleted_value (default is 'deleted')._  **Any records not matching this string will be treated normally.**"

Before merging this in, I would ask that you add additional tests that drive out the specific nature of these changes before. Ie: Setup a model that acts in the nature described and test it's behavior against a the non-custom delete string (ala: ParanoidString vs ParanoidDeleteString).

**Comment by garysweaver** [comment]
I added tests that test the specific nature of the revised functionality that are in the existing patch using the existing ParanoidString, using the existing tests as a guide for what would be expected. If those don't work, let me know specifically what you'd like me to change about them, and I'll do my best. Thanks!

**Comment by chuckg** [comment]
Your tests change the setup of the application and then modify the
assertions in the test which was created primarily to validate the test
setup and basic core functionality. To drive it out these changes directly,
you might create a test who's sole purpose is to create a ParanoidString
with a nil, one with a string not matching the specified string, and then
go through the process of deleting them and double check they're returned
(or not) correctly.

Isolation of tests is the primary driving force behind this. As the gem
grows and the functionality becomes more complex, implicit tests (which
I'm guilty of writing as well) become harder to understand and maintain.

**Comment by aake** [comment]
Sorry for the multiple commit references. My dev environment is running in a VM on my mac and the date was out of synch. I tried resolving this a couple of times before I was successful (51d7759 which is the same as the pull request).

**Comment by chuckg** [comment]
Thanks for updating your tests Peter. I'm utterly on holiday, but I'll take
a peek at your changes and merge when I return.

**Comment by chuckg** [comment]
Similar functionality was just merged with Issue #81.  Please refer to that issue for any further discussion.

**Pull request closed without merging**
