### PR TITLE
Added 

### PR DESCRIPTION
**Pull request by h0jeZvgoxFepBQ2C**
Found a serious bug in this gem (method destroy! and destroy mutliple times are affected):

When I have a parent-object with some child-objects and i hard delete the parent object - the child objects doenst become hard deleted too!

Its because of the implementation with delete_all!

The api says about delete_all:
...
Be careful with relations though, in particular :dependent rules defined on associations are not honored. 
...

I added a test which shows the problem clearly...

### CODE REVIEW

**Comment by h0jeZvgoxFepBQ2C** [comment]
And i cleaned up the migrations in test_helper a bit

**Comment by goncalossilva** [comment]
I'm trying to find a fix for this but I haven't had much time on my hands lately. Just commenting so that you know that I'm _not_ ignoring this.

**Comment by borisruf** [comment]
Hi, I was wondering if there is any progress on this issue? Thanks.

**Comment by goncalossilva** [comment]
I've played around a little but haven't got s solution. I'm not currently using this gem, which makes it harder. I'll gladly accept patches, though.

**Pull request closed without merging**
